In [5]:
import pandas as pd

In [7]:
df1=pd.read_excel("VendorProducts.xlsx",sheet_name="Items")

df2=pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")

In [8]:
df1.columns

Index(['Picture', 'Id', 'Name', 'Secondary Name', 'Barcode', 'Code', 'Price',
       'Description', 'Secondary Description', 'Sub Description',
       'Secondary Sub Description', 'Menu', 'Brand', 'Secondary Brand',
       'Has Collections'],
      dtype='str')

In [12]:
df3=df1["Price"]

In [13]:
df4=list[df3]

In [22]:
df4

list[0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: str]

In [63]:
for i in df3:
    x=i.replace("د.ع","")
    y=int(x.replace(",",""))
    print(pd.Series(y))

0    25000
dtype: int64
0    300000
dtype: int64
0    30000
dtype: int64
0    0
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    18000
dtype: int64
0    15000
dtype: int64
0    7750
dtype: int64
0    15500
dtype: int64
0    65000
dtype: int64
0    3500
dtype: int64
0    19000
dtype: int64
0    38000
dtype: int64
0    15500
dtype: int64
0    8000
dtype: int64
0    115500
dtype: int64
0    6500
dtype: int64
0    30000
dtype: int64
0    20000
dtype: int64
0    4000
dtype: int64
0    30000
dtype: int64
0    4000
dtype: int64
0    32000
dtype: int64
0    4000
dtype: int64
0    30000
dtype: int64
0    45000
dtype: int64
0    37000
dtype: int64
0    30000
dtype: int64
0    10000
dtype: int64
0    3500
dtype: int64
0    3500
dtype: int64
0    45000
dtype: int64
0    45000
dtype: int64
0    15000
dtype: int64
0    50000
dtype: int64
0    7500
dtype: int64
0    120000
dtype: int64
0    15000
dtype: int64
0    5000
dtype: int64
0    120000
dtype: int64
0    5000
dtype: int64
0    4500
dtype: int64
0    5000
dtype: int64
0    75000
dtype: int64
0    13000
dtype: int64
0    75000
dtype: int64
0    6500
dtype: int64
0    19000
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    28000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    8500
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    17000
dtype: int64
0    15000
dtype: int64
0    19750
dtype: int64
0    19750
dtype: int64
0    27000
dtype: int64
0    27000
dtype: int64
0    30000
dtype: int64
0    30500
dtype: int64
0    23000
dtype: int64
0    9000
dtype: int64
0    25000
dtype: int64
0    9000
dtype: int64
0    25000
dtype: int64
0    32000
dtype: int64
0    16000
dtype: int64
0    9000
dtype: int64
0    27000
dtype: int64
0    9000
dtype: int64
0    27000
dtype: int64
0    370000
dtype: int64
0    10500
dtype: int64
0    10500
dtype: int64
0    37500
dtype: int64
0    60000
dtype: int64
0    7000
dtype: int64
0    120000
dtype: int64
0    18500
dtype: int64
0    25000
dtype: int64
0    39000
dtype: int64
0    22000
dtype: int64
0    19000
dtype: int64
0    163250
dtype: int64
0    255250
dtype: int64
0    72000
dtype: int64
0    45000
dtype: int64
0    124250
dtype: int64
0    28750
dtype: int64
0    109250
dtype: int64
0    26250
dtype: int64
0    26250
dtype: int64
0    71000
dtype: int64
0    92500
dtype: int64
0    18250
dtype: int64
0    92500
dtype: int64
0    50000
dtype: int64
0    25000
dtype: int64
0    66000
dtype: int64
0    25000
dtype: int64
0    25000
dtype: int64
0    35000
dtype: int64
0    25000
dtype: int64
0    23750
dtype: int64
0    25000
dtype: int64
0    28000
dtype: int64
0    19000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    25000
dtype: int64
0    8000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    7000
dtype: int64
0    30000
dtype: int64
0    18000
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    17000
dtype: int64
0    17000
dtype: int64
0    17000
dtype: int64
0    17000
dtype: int64
0    8000
dtype: int64
0    15000
dtype: int64
0    8000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    12000
dtype: int64
0    12000
dtype: int64
0    15000
dtype: int64
0    17000
dtype: int64
0    17000
dtype: int64
0    17000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    17000
dtype: int64
0    8000
dtype: int64
0    31000
dtype: int64
0    15000
dtype: int64
0    34000
dtype: int64
0    15000
dtype: int64
0    34000
dtype: int64
0    40000
dtype: int64
0    17000
dtype: int64
0    55500
dtype: int64
0    17000
dtype: int64
0    60000
dtype: int64
0    270250
dtype: int64
0    270250
dtype: int64
0    150000
dtype: int64
0    150000
dtype: int64
0    70000
dtype: int64
0    60000
dtype: int64
0    60000
dtype: int64
0    105000
dtype: int64
0    44000
dtype: int64
0    12000
dtype: int64
0    8500
dtype: int64
0    16000
dtype: int64
0    8500
dtype: int64
0    413250
dtype: int64
0    8500
dtype: int64
0    25000
dtype: int64
0    15000
dtype: int64
0    35000
dtype: int64
0    35000
dtype: int64
0    10000
dtype: int64
0    3500
dtype: int64
0    12000
dtype: int64
0    25000
dtype: int64
0    30000
dtype: int64
0    68000
dtype: int64
0    365500
dtype: int64
0    129000
dtype: int64
0    123250
dtype: int64
0    158000
dtype: int64
0    129000
dtype: int64
0    123250
dtype: int64
0    129000
dtype: int64
0    123250
dtype: int64
0    346750
dtype: int64
0    53500
dtype: int64
0    94250
dtype: int64
0    43500
dtype: int64
0    82000
dtype: int64
0    82000
dtype: int64
0    46500
dtype: int64
0    9000
dtype: int64
0    9000
dtype: int64
0    4000
dtype: int64
0    0
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    78000
dtype: int64
0    25000
dtype: int64
0    9500
dtype: int64
0    3000
dtype: int64
0    3000
dtype: int64
0    3000
dtype: int64
0    24000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    14000
dtype: int64
0    10000
dtype: int64
0    9000
dtype: int64
0    10000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    14000
dtype: int64
0    25000
dtype: int64
0    15000
dtype: int64
0    19500
dtype: int64
0    34750
dtype: int64
0    34750
dtype: int64
0    34750
dtype: int64
0    19000
dtype: int64
0    57000
dtype: int64
0    55000
dtype: int64
0    1
dtype: int64
0    25000
dtype: int64
0    50000
dtype: int64
0    20000
dtype: int64
0    16000
dtype: int64
0    435000
dtype: int64
0    28000
dtype: int64
0    32000
dtype: int64
0    25000
dtype: int64
0    28000
dtype: int64
0    6000
dtype: int64
0    18000
dtype: int64
0    18000
dtype: int64
0    16000
dtype: int64
0    17500
dtype: int64
0    12000
dtype: int64
0    18000
dtype: int64
0    95000
dtype: int64
0    18000
dtype: int64
0    20000
dtype: int64
0    18000
dtype: int64
0    18000
dtype: int64
0    20000
dtype: int64
0    3500
dtype: int64
0    4000
dtype: int64
0    14000
dtype: int64
0    27500
dtype: int64
0    25000
dtype: int64
0    22000
dtype: int64
0    20000
dtype: int64
0    22000
dtype: int64
0    22000
dtype: int64
0    22000
dtype: int64
0    22000
dtype: int64
0    158000
dtype: int64
0    152750
dtype: int64
0    159500
dtype: int64
0    159500
dtype: int64
0    145000
dtype: int64
0    153000
dtype: int64
0    13750
dtype: int64
0    530000
dtype: int64
0    17500
dtype: int64
0    24000
dtype: int64
0    26000
dtype: int64
0    40000
dtype: int64
0    75500
dtype: int64
0    70000
dtype: int64
0    116250
dtype: int64
0    89000
dtype: int64
0    59000
dtype: int64
0    28000
dtype: int64
0    28000
dtype: int64
0    14750
dtype: int64
0    23750
dtype: int64
0    31250
dtype: int64
0    14500
dtype: int64
0    11250
dtype: int64
0    15750
dtype: int64
0    295000
dtype: int64
0    17000
dtype: int64
0    295000
dtype: int64
0    28250
dtype: int64
0    295000
dtype: int64
0    16750
dtype: int64
0    17250
dtype: int64
0    19750
dtype: int64
0    295000
dtype: int64
0    295000
dtype: int64
0    19250
dtype: int64
0    295000
dtype: int64
0    16000
dtype: int64
0    295000
dtype: int64
0    25500
dtype: int64
0    295000
dtype: int64
0    14250
dtype: int64
0    31250
dtype: int64
0    295000
dtype: int64
0    24250
dtype: int64
0    295000
dtype: int64
0    38750
dtype: int64
0    13250
dtype: int64
0    25000
dtype: int64
0    21500
dtype: int64
0    295000
dtype: int64
0    25000
dtype: int64
0    25000
dtype: int64
0    18750
dtype: int64
0    295000
dtype: int64
0    17500
dtype: int64
0    295000
dtype: int64
0    14500
dtype: int64
0    295000
dtype: int64
0    20750
dtype: int64
0    19000
dtype: int64
0    295000
dtype: int64
0    20000
dtype: int64
0    25250
dtype: int64
0    295000
dtype: int64
0    30750
dtype: int64
0    9750
dtype: int64
0    24000
dtype: int64
0    9000
dtype: int64
0    24000
dtype: int64
0    55000
dtype: int64
0    27750
dtype: int64
0    8000
dtype: int64
0    5750
dtype: int64
0    26000
dtype: int64
0    7250
dtype: int64
0    4000
dtype: int64
0    22000
dtype: int64
0    5000
dtype: int64
0    5250
dtype: int64
0    7250
dtype: int64
0    6500
dtype: int64
0    5250
dtype: int64
0    3250
dtype: int64
0    7250
dtype: int64
0    139500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    6500
dtype: int64
0    85750
dtype: int64
0    98250
dtype: int64
0    338250
dtype: int64
0    775000
dtype: int64
0    59000
dtype: int64
0    15000
dtype: int64
0    12000
dtype: int64
0    12000
dtype: int64
0    12000
dtype: int64
0    90000
dtype: int64
0    50000
dtype: int64
0    22000
dtype: int64
0    24000
dtype: int64
0    169000
dtype: int64
0    22000
dtype: int64
0    22000
dtype: int64
0    50000
dtype: int64
0    68000
dtype: int64
0    68000
dtype: int64
0    39000
dtype: int64
0    100750
dtype: int64
0    68000
dtype: int64
0    59000
dtype: int64
0    68000
dtype: int64
0    68000
dtype: int64
0    68000
dtype: int64
0    3500
dtype: int64
0    45000
dtype: int64
0    45000
dtype: int64
0    75000
dtype: int64
0    8500
dtype: int64
0    33000
dtype: int64
0    5000
dtype: int64
0    100750
dtype: int64
0    4000
dtype: int64
0    9500
dtype: int64
0    14000
dtype: int64
0    23250
dtype: int64
0    31000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    70000
dtype: int64
0    110000
dtype: int64
0    76750
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    23250
dtype: int64
0    129000
dtype: int64
0    24000
dtype: int64
0    71500
dtype: int64
0    23000
dtype: int64
0    56000
dtype: int64
0    7000
dtype: int64
0    23000
dtype: int64
0    15000
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    5000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    20000
dtype: int64
0    20000
dtype: int64
0    12000
dtype: int64
0    7000
dtype: int64
0    15000
dtype: int64
0    3000
dtype: int64
0    5000
dtype: int64
0    8000
dtype: int64
0    14000
dtype: int64
0    231500
dtype: int64
0    18750
dtype: int64
0    14000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    975000
dtype: int64
0    367000
dtype: int64
0    975000
dtype: int64
0    681000
dtype: int64
0    681000
dtype: int64
0    900000
dtype: int64
0    825000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    6000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    14000
dtype: int64
0    14000
dtype: int64
0    14000
dtype: int64
0    14000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    4500
dtype: int64
0    4500
dtype: int64
0    14000
dtype: int64
0    29000
dtype: int64
0    15000
dtype: int64
0    4500
dtype: int64
0    14000
dtype: int64
0    25000
dtype: int64
0    14000
dtype: int64
0    22000
dtype: int64
0    24000
dtype: int64
0    15000
dtype: int64
0    14000
dtype: int64
0    70000
dtype: int64
0    15000
dtype: int64
0    60000
dtype: int64
0    14000
dtype: int64
0    18000
dtype: int64
0    274000
dtype: int64
0    18000
dtype: int64
0    79000
dtype: int64
0    18000
dtype: int64
0    18000
dtype: int64
0    18000
dtype: int64
0    10000
dtype: int64
0    18000
dtype: int64
0    136500
dtype: int64
0    18000
dtype: int64
0    18000
dtype: int64
0    136500
dtype: int64
0    178250
dtype: int64
0    130000
dtype: int64
0    114000
dtype: int64
0    173500
dtype: int64
0    36500
dtype: int64
0    127000
dtype: int64
0    170500
dtype: int64
0    121000
dtype: int64
0    131750
dtype: int64
0    1500
dtype: int64
0    100750
dtype: int64
0    170000
dtype: int64
0    50000
dtype: int64
0    50000
dtype: int64
0    58000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    95000
dtype: int64
0    75000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    65000
dtype: int64
0    40000
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    116250
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    37000
dtype: int64
0    35000
dtype: int64
0    75000
dtype: int64
0    82000
dtype: int64
0    114000
dtype: int64
0    84000
dtype: int64
0    48000
dtype: int64
0    128000
dtype: int64
0    95000
dtype: int64
0    89000
dtype: int64
0    51000
dtype: int64
0    64000
dtype: int64
0    51000
dtype: int64
0    31000
dtype: int64
0    40000
dtype: int64
0    9000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    7500
dtype: int64
0    40000
dtype: int64
0    75000
dtype: int64
0    75000
dtype: int64
0    75000
dtype: int64
0    50000
dtype: int64
0    43500
dtype: int64
0    236500
dtype: int64
0    43500
dtype: int64
0    50000
dtype: int64
0    50000
dtype: int64
0    13250
dtype: int64
0    2000
dtype: int64
0    3000
dtype: int64
0    3500
dtype: int64
0    2500
dtype: int64
0    75000
dtype: int64
0    26000
dtype: int64
0    2000
dtype: int64
0    2000
dtype: int64
0    25000
dtype: int64
0    75000
dtype: int64
0    34500
dtype: int64
0    75000
dtype: int64
0    19000
dtype: int64
0    96000
dtype: int64
0    9000
dtype: int64
0    127000
dtype: int64
0    127000
dtype: int64
0    85250
dtype: int64
0    6000
dtype: int64
0    108500
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    90000
dtype: int64
0    62000
dtype: int64
0    33500
dtype: int64
0    59000
dtype: int64
0    162750
dtype: int64
0    124000
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    99750
dtype: int64
0    83000
dtype: int64
0    65000
dtype: int64
0    107000
dtype: int64
0    147000
dtype: int64
0    50000
dtype: int64
0    128000
dtype: int64
0    39000
dtype: int64
0    42000
dtype: int64
0    53000
dtype: int64
0    48000
dtype: int64
0    108000
dtype: int64
0    46000
dtype: int64
0    49000
dtype: int64
0    57000
dtype: int64
0    42000
dtype: int64
0    229000
dtype: int64
0    208000
dtype: int64
0    203000
dtype: int64
0    85000
dtype: int64
0    118000
dtype: int64
0    193000
dtype: int64
0    74000
dtype: int64
0    65000
dtype: int64
0    110000
dtype: int64
0    113000
dtype: int64
0    63000
dtype: int64
0    8000
dtype: int64
0    7000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    12000
dtype: int64
0    15000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    8000
dtype: int64
0    8000
dtype: int64
0    6000
dtype: int64
0    7000
dtype: int64
0    8000
dtype: int64
0    163000
dtype: int64
0    137500
dtype: int64
0    143500
dtype: int64
0    165500
dtype: int64
0    231750
dtype: int64
0    204000
dtype: int64
0    100000
dtype: int64
0    26750
dtype: int64
0    10000
dtype: int64
0    15000
dtype: int64
0    40000
dtype: int64
0    22000
dtype: int64
0    28000
dtype: int64
0    28000
dtype: int64
0    93000
dtype: int64
0    131250
dtype: int64
0    115500
dtype: int64
0    92750
dtype: int64
0    0
dtype: int64
0    0
dtype: int64
0    7500
dtype: int64
0    100000
dtype: int64
0    90000
dtype: int64
0    120000
dtype: int64
0    7500
dtype: int64
0    87000
dtype: int64
0    65000
dtype: int64
0    65000
dtype: int64
0    4500
dtype: int64
0    40000
dtype: int64
0    40000
dtype: int64
0    60000
dtype: int64
0    60000
dtype: int64
0    70000
dtype: int64
0    65000
dtype: int64
0    120000
dtype: int64
0    120000
dtype: int64
0    346000
dtype: int64
0    65000
dtype: int64
0    65000
dtype: int64
0    38000
dtype: int64
0    40000
dtype: int64
0    131250
dtype: int64
0    106500
dtype: int64
0    100500
dtype: int64
0    100750
dtype: int64
0    105500
dtype: int64
0    150000
dtype: int64
0    150000
dtype: int64
0    130500
dtype: int64
0    115500
dtype: int64
0    192000
dtype: int64
0    192000
dtype: int64
0    192000
dtype: int64
0    421750
dtype: int64
0    123000
dtype: int64
0    76750
dtype: int64
0    396000
dtype: int64
0    135000
dtype: int64
0    396000
dtype: int64
0    85000
dtype: int64
0    195000
dtype: int64
0    85000
dtype: int64
0    5000
dtype: int64
0    85750
dtype: int64
0    75500
dtype: int64
0    100000
dtype: int64
0    15000
dtype: int64
0    52750
dtype: int64
0    121000
dtype: int64
0    131750
dtype: int64
0    69500
dtype: int64
0    74500
dtype: int64
0    162750
dtype: int64
0    108500
dtype: int64
0    48500
dtype: int64
0    46500
dtype: int64
0    248000
dtype: int64
0    170500
dtype: int64
0    170500
dtype: int64
0    101250
dtype: int64
0    6500
dtype: int64
0    42000
dtype: int64
0    80000
dtype: int64
0    80000
dtype: int64
0    35000
dtype: int64
0    65000
dtype: int64
0    42250
dtype: int64
0    74000
dtype: int64
0    123250
dtype: int64
0    66750
dtype: int64
0    100750
dtype: int64
0    66750
dtype: int64
0    71750
dtype: int64
0    71750
dtype: int64
0    59000
dtype: int64
0    66750
dtype: int64
0    63500
dtype: int64
0    66750
dtype: int64
0    542500
dtype: int64
0    434000
dtype: int64
0    434000
dtype: int64
0    91500
dtype: int64
0    151750
dtype: int64
0    100750
dtype: int64
0    265000
dtype: int64
0    265000
dtype: int64
0    465000
dtype: int64
0    364250
dtype: int64
0    4000
dtype: int64
0    64500
dtype: int64
0    4000
dtype: int64
0    3500
dtype: int64
0    13000
dtype: int64
0    45000
dtype: int64
0    18500
dtype: int64
0    25750
dtype: int64
0    25000
dtype: int64
0    25000
dtype: int64
0    68000
dtype: int64
0    25000
dtype: int64
0    25000
dtype: int64
0    13250
dtype: int64
0    30000
dtype: int64
0    25000
dtype: int64
0    5000
dtype: int64
0    25000
dtype: int64
0    15000
dtype: int64
0    25000
dtype: int64
0    0
dtype: int64
0    2500
dtype: int64
0    10000
dtype: int64
0    3500
dtype: int64
0    0
dtype: int64
0    3500
dtype: int64
0    80500
dtype: int64
0    100750
dtype: int64
0    116250
dtype: int64
0    207750
dtype: int64
0    108000
dtype: int64
0    105500
dtype: int64
0    3500
dtype: int64
0    116250
dtype: int64
0    100750
dtype: int64
0    147250
dtype: int64
0    0
dtype: int64
0    5000
dtype: int64
0    5000
dtype: int64
0    7000
dtype: int64
0    7000
dtype: int64
0    8000
dtype: int64
0    7000
dtype: int64
0    5000
dtype: int64
0    3500
dtype: int64
0    139500
dtype: int64
0    7500
dtype: int64
0    7500
dtype: int64
0    5000
dtype: int64
0    6000
dtype: int64
0    3500
dtype: int64
0    62000
dtype: int64
0    29500
dtype: int64
0    20250
dtype: int64
0    65000
dtype: int64
0    162500
dtype: int64
0    142250
dtype: int64
0    80500
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    15000
dtype: int64
0    30000
dtype: int64
0    158250
dtype: int64
0    126750
dtype: int64
0    15000
dtype: int64
0    10000
dtype: int64
0    10000
dtype: int64
0    15000
dtype: int64
0    10000
dtype: int64
0    15000
dtype: int64
0    6000
dtype: int64
0    13000
dtype: int64
0    25000
dtype: int64
0    4500
dtype: int64
0    30000
dtype: int64
0    12000
dtype: int64
0    14000
dtype: int64
0    42000
dtype: int64
0    29000
dtype: int64
0    9000
dtype: int64
0    8000
dtype: int64
0    4000
dtype: int64
0    8500
dtype: int64
0    10000
dtype: int64
0    8000
dtype: int64
0    8000
dtype: int64
0    8000
dtype: int64
0    5000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    6000
dtype: int64
0    116250
dtype: int64
0    85250
dtype: int64
0    98250
dtype: int64
0    69750
dtype: int64
0    39250
dtype: int64
0    131750
dtype: int64
0    37750
dtype: int64
0    74500
dtype: int64
0    72750
dtype: int64
0    131750
dtype: int64
0    117750
dtype: int64
0    59000
dtype: int64
0    120000
dtype: int64
0    69750

In [67]:
df1[["Picture","Id","Price"]]

                                                 Picture      Id       Price
0      https://www.storeakmedia.com/storeak-erp/Store...  390188   25,000د.ع
1      https://www.storeakmedia.com/storeak-erp/Store...  390187  300,000د.ع
2      https://www.storeakmedia.com/storeak-erp/Store...  390186   30,000د.ع
3      https://www.storeakmedia.com/storeak-erp/Store...  390185       00د.ع
4      https://www.storeakmedia.com/storeak-erp/Store...  390177   15,000د.ع
...                                                  ...     ...         ...
24697  https://www.storeakmedia.com/storeak-erp/Store...  315019   16,500د.ع
24698  https://www.storeakmedia.com/storeak-erp/Store...  315018   12,000د.ع
24699  https://www.storeakmedia.com/storeak-erp/Store...  314993   10,500د.ع
24700  https://www.storeakmedia.com/storeak-erp/Store...  314992   15,000د.ع
24701  https://www.storeakmedia.com/storeak-erp/Store...  314991   22,500د.ع

[24702 rows x 3 columns]

In [68]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 24702 entries, 0 to 24701
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Picture                    24300 non-null  str
 1   Id                         24702 non-null  int64
 2   Name                       24702 non-null  str
 3   Secondary Name             24702 non-null  str
 4   Barcode                    22041 non-null  str
 5   Code                       21993 non-null  str
 6   Price                      24702 non-null  str
 7   Description                24645 non-null  str
 8   Secondary Description      24644 non-null  str
 9   Sub Description            24601 non-null  str
 10  Secondary Sub Description  4 non-null      str
 11  Menu                       24699 non-null  str
 12  Brand                      24699 non-null  str
 13  Secondary Brand            24696 non-null  str
 14  Has Collections            24702 non-null  str
dtypes: int64(1), str(14)
memory usage: 2.8 MB

In [71]:
df1.describe()

                  Id
count   24702.000000
mean   330583.440936
std     12701.598678
min    314991.000000
25%    321257.250000
50%    327496.500000
75%    334544.750000
max    390188.000000

In [82]:
dic={"name":["umar","farooq","ali"],"age":[20,21,23],"class":["BSSE","BSCS","BSIT"]}
dfs=pd.DataFrame(dic)
dfg=dfs.to_csv("newdata.csv",index=False)

In [86]:
dfh=pd.read_csv("newdata.csv")

In [88]:
currentnumber=len(dfh["name"])
currentnumber

3